version: "3"
services:
  app:
    build: ./
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    ports:
      - "3000:3000"
    command: >
      sh -c "bundle i && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--default-authentication-plugin=mysql_native_password",
      ]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=example
    ports:
      - 8081:80
    volumes:
      - /sessions
volumes:
  bundle:
